#!/usr/bin/env node
/*
 * build-api.js — generates the machine-readable API for agents.
 *
 * The two human-edited JSON files remain the single source of truth.
 * This script merges them into api/programs.json (a unified array with a
 * `dataset` tag on each program, plus facets + schema for agent discovery).
 *
 * Run before deploying whenever the source data changes:
 *   node build-api.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'api');
const OUT_FILE = path.join(OUT_DIR, 'programs.json');

const SOURCES = [
  { dataset: 'residential', file: 'startup-programs-data.json' },
  { dataset: 'traditional', file: 'traditional-programs-data.json' },
];

const STATUS_LEGEND = {
  rolling: 'Accepts applications on a rolling/always-open basis',
  open: 'A specific cohort window is currently open',
  'closing-soon': 'Open but with an imminent deadline',
  'opening-soon': 'Next cohort applications announced, opening shortly',
  running: 'Cohort currently in session',
  closed: 'Latest cohort closed; check site for next cycle',
};

const SCHEMA = {
  name: 'Program name',
  type: 'Program category (e.g. Accelerator, Residency, Hacker House)',
  dataset: 'residential | traditional',
  city: 'City',
  country: 'Country',
  lat: 'Latitude (number)',
  lng: 'Longitude (number)',
  focus: 'Areas of focus (comma-separated text)',
  operator: 'Organization or person running the program',
  stage: 'Founder stage served (e.g. Pre-seed / very early)',
  status: 'Recruiting status enum: ' + Object.keys(STATUS_LEGEND).join(' | '),
  status_detail: 'Human-readable recruiting detail',
  domain: 'Program website domain',
  url: 'Application / visit URL',
  highlight: 'Optional differentiator / key fact',
};

function countBy(items, key) {
  const out = {};
  for (const it of items) {
    const v = it[key];
    if (v === undefined || v === null || v === '') continue;
    out[v] = (out[v] || 0) + 1;
  }
  return out;
}

const programs = [];
for (const { dataset, file } of SOURCES) {
  const raw = JSON.parse(fs.readFileSync(path.join(ROOT, file), 'utf8'));
  for (const p of raw.programs) programs.push({ dataset, ...p });
}

const facets = {
  dataset: countBy(programs, 'dataset'),
  type: countBy(programs, 'type'),
  country: countBy(programs, 'country'),
  status: countBy(programs, 'status'),
};

const output = {
  meta: {
    title: 'Founder LAB MAP — unified program API',
    tagline: 'Where founders find all kinds of living and building support programs.',
    compiled: new Date().toISOString().slice(0, 10),
    note: 'Generated by build-api.js from the source JSON files. Do not hand-edit. ' +
      'Recruiting status reflects best-available public info and changes frequently — confirm on each program site.',
    status_legend: STATUS_LEGEND,
    query_help:
      'The /dashboard page is filterable via URL query params: ' +
      '?dataset=all|residential|traditional&q=<text>&type=<type>&country=<country>&status=<status>&focus=<text>&sort=<field>',
  },
  schema: SCHEMA,
  count: programs.length,
  facets,
  programs,
};

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, JSON.stringify(output, null, 2) + '\n');
console.log(`Wrote ${OUT_FILE}: ${programs.length} programs ` +
  `(${facets.dataset.residential || 0} residential, ${facets.dataset.traditional || 0} traditional).`);
